# Generated by Django 3.0.5 on 2021-06-23 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0005_auto_20210623_2357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('smsPrefix', models.CharField(blank=True, max_length=264, null=True)),
                ('letterPrefix', models.CharField(blank=True, max_length=264, null=True)),
                ('description', models.CharField(blank=True, max_length=264, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('zone', models.CharField(max_length=264)),
                ('shortcode', models.CharField(max_length=264)),
                ('call_center_no', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_societies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleSocieties', to='UserManagement.user_roles')),
                ('society_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSocieties', to='societies.society')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSocieties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='society_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(blank=True, max_length=264, null=True)),
                ('setting_value', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('society_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societies.society')),
            ],
        ),
        migrations.AddField(
            model_name='society',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ZoneSociety', to='societies.zones'),
        ),
    ]
