# Generated by Django 3.2.4 on 2021-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_size',
            name='ize',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='plot_size',
            name='mysqlID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
