# Generated by Django 3.0.5 on 2021-06-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=264, null=True)),
                ('sms_code', models.CharField(blank=True, max_length=264, null=True)),
                ('network', models.CharField(blank=True, max_length=264, null=True)),
                ('received_message', models.TextField(blank=True, max_length=10000, null=True)),
                ('response_message', models.TextField(blank=True, max_length=10000, null=True)),
                ('sms_sent', models.BooleanField(blank=True, null=True)),
                ('is_billed', models.BooleanField(blank=True, null=True)),
                ('billed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('society_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocietySMS', to='societies.society')),
            ],
        ),
    ]
