# Generated by Django 3.2.4 on 2021-07-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_auto_20210714_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot_size',
            old_name='ize',
            new_name='size',
        ),
    ]
