# Generated by Django 3.0.5 on 2021-06-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_sms_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_log',
            name='society_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SocietySMS', to='societies.society'),
        ),
    ]
