# Generated by Django 3.2.4 on 2021-07-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_rename_ize_plot_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_size',
            name='society_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societyPlotSize', to='societies.society'),
        ),
    ]
