# Generated by Django 3.0.5 on 2021-06-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0006_auto_20210625_2213'),
        ('societies', '0003_auto_20210624_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_log',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society_settings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='society',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ZoneSociety', to='societies.zones'),
        ),
        migrations.AlterField(
            model_name='society_settings',
            name='society_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='societies.society'),
        ),
        migrations.AlterField(
            model_name='user_societies',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RoleSocieties', to='UserManagement.user_roles'),
        ),
        migrations.AlterField(
            model_name='user_societies',
            name='society_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSocieties', to='societies.society'),
        ),
        migrations.AlterField(
            model_name='user_societies',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSocieties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='sms_log',
            table='sms_log',
        ),
        migrations.AlterModelTable(
            name='society',
            table='society',
        ),
        migrations.AlterModelTable(
            name='society_settings',
            table='society_settings',
        ),
        migrations.AlterModelTable(
            name='user_societies',
            table='user_societies',
        ),
        migrations.AlterModelTable(
            name='zones',
            table='zones',
        ),
        migrations.CreateModel(
            name='report_zone_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_process', models.IntegerField(blank=True, null=True)),
                ('total_pending', models.IntegerField(blank=True, null=True)),
                ('total_cancelled', models.IntegerField(blank=True, null=True)),
                ('total_rejected', models.IntegerField(blank=True, null=True)),
                ('process_types_total', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('zone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.zones')),
            ],
            options={
                'db_table': 'report_zone_process',
            },
        ),
        migrations.CreateModel(
            name='report_user_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_process', models.IntegerField(blank=True, null=True)),
                ('total_pending', models.IntegerField(blank=True, null=True)),
                ('total_approved', models.IntegerField(blank=True, null=True)),
                ('total_cancelled', models.IntegerField(blank=True, null=True)),
                ('total_rejected', models.IntegerField(blank=True, null=True)),
                ('process_types_total', models.CharField(blank=True, max_length=264, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('society_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.society')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user_roles')),
                ('zone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.zones')),
            ],
            options={
                'db_table': 'report_user_process',
            },
        ),
        migrations.CreateModel(
            name='report_society_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_process', models.IntegerField(blank=True, null=True)),
                ('total_pending', models.IntegerField(blank=True, null=True)),
                ('total_approved', models.IntegerField(blank=True, null=True)),
                ('total_cancelled', models.IntegerField(blank=True, null=True)),
                ('total_rejected', models.IntegerField(blank=True, null=True)),
                ('process_types_total', models.CharField(blank=True, max_length=264, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('society_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.society')),
                ('zone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.zones')),
            ],
            options={
                'db_table': 'report_society_process',
            },
        ),
    ]
