# Generated by Django 3.2.4 on 2021-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_plot_size_society_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='mysql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
