# Generated by Django 3.2.4 on 2021-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0005_plots_mysql_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='memberID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
