# Generated by Django 3.2.4 on 2021-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0006_members_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
