# Generated by Django 3.2.4 on 2021-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0007_alter_members_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_plots',
            name='memberPlotID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
