# Generated by Django 3.2.4 on 2021-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0008_member_plots_memberplotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_meta',
            name='meta_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
