# Generated by Django 3.2.4 on 2021-07-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0009_member_meta_meta_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='memberID',
            new_name='mysql_id',
        ),
        migrations.RenameField(
            model_name='plot_size',
            old_name='mysqlID',
            new_name='mysql_id',
        ),
    ]
