# Generated by Django 3.2.4 on 2021-07-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0010_auto_20210715_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_plots',
            old_name='memberPlotID',
            new_name='mysql_id',
        ),
    ]
