# Generated by Django 3.2.4 on 2021-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0011_rename_memberplotid_member_plots_mysql_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='mysql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='otc_payment_token_expiry',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
