# Generated by Django 3.2.4 on 2021-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0012_auto_20210715_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='mysql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
