# Generated by Django 3.2.4 on 2021-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0013_letters_mysql_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='president_barcode',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
