# Generated by Django 3.2.4 on 2021-07-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0014_letters_president_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letters',
            old_name='qr_barcode',
            new_name='qr_code',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='qr_barcode_hash',
            new_name='qr_code_hash',
        ),
    ]
