# Generated by Django 3.2.4 on 2021-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0015_auto_20210715_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='item_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.members'),
        ),
    ]
