# Generated by Django 3.2.4 on 2021-07-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0016_auto_20210716_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='model',
            new_name='contact_type',
        ),
    ]
