# Generated by Django 3.2.5 on 2021-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_installments_mysql_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='mysql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
