# Generated by Django 3.2.5 on 2021-07-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_documents_mysql_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='file_stype',
            new_name='file_type',
        ),
    ]
