# Generated by Django 3.2.4 on 2021-07-29 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysql_id', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=264, null=True)),
                ('member_id', models.CharField(blank=True, max_length=264, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=264, null=True)),
                ('plot_block_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('plot_address', models.CharField(blank=True, max_length=264, null=True)),
                ('full_name', models.CharField(blank=True, max_length=264, null=True)),
                ('cnic', models.CharField(blank=True, max_length=264, null=True)),
                ('type', models.CharField(blank=True, max_length=264, null=True)),
                ('process_data', models.CharField(blank=True, max_length=100000, null=True)),
                ('process_data_back', models.CharField(blank=True, max_length=26400, null=True)),
                ('status', models.CharField(blank=True, max_length=264, null=True)),
                ('street_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('process_no', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersProcessassigne', to=settings.AUTH_USER_MODEL)),
                ('plot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.plots')),
                ('society_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societyProcess', to='societies.society')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='process_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'process_types',
            },
        ),
        migrations.CreateModel(
            name='process_types_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(blank=True, max_length=264, null=True)),
                ('meta_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processTypes', to='process.process_types')),
            ],
            options={
                'db_table': 'process_types_meta',
            },
        ),
        migrations.CreateModel(
            name='process_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=264, null=True)),
                ('status', models.CharField(blank=True, max_length=264, null=True)),
                ('log', models.CharField(blank=True, max_length=264, null=True)),
                ('comments', models.CharField(blank=True, max_length=264, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('process_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProcessComments', to='process.process')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processUsersComments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_comments',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processtype', to='process.process_types'),
        ),
        migrations.AddField(
            model_name='process',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersProcess', to=settings.AUTH_USER_MODEL),
        ),
    ]
