# Generated by Django 3.0.5 on 2021-06-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('societies', '0004_auto_20210625_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'process_types',
            },
        ),
        migrations.CreateModel(
            name='process_types_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=264)),
                ('meta_value', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processTypes', to='process.process_types')),
            ],
            options={
                'db_table': 'process_types_meta',
            },
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(blank=True, max_length=264, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=264, null=True)),
                ('member_id', models.CharField(blank=True, max_length=264, null=True)),
                ('plot_id', models.CharField(blank=True, max_length=264, null=True)),
                ('plot_no', models.IntegerField(blank=True, null=True)),
                ('plot_block_no', models.IntegerField(blank=True, null=True)),
                ('plot_address', models.CharField(blank=True, max_length=264, null=True)),
                ('full_name', models.CharField(blank=True, max_length=264, null=True)),
                ('cnic', models.CharField(blank=True, max_length=264, null=True)),
                ('type', models.CharField(blank=True, max_length=264, null=True)),
                ('process_data', models.CharField(blank=True, max_length=264, null=True)),
                ('process_data_back', models.CharField(blank=True, max_length=264, null=True)),
                ('status', models.CharField(blank=True, max_length=264, null=True)),
                ('street_no', models.IntegerField(blank=True, null=True)),
                ('process_no', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('society_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societyProcess', to='societies.society')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processtype', to='process.process_types')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersProcess', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process',
            },
        ),
    ]
