# Generated by Django 3.2.4 on 2021-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='mysql_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
