# Generated by Django 3.2.4 on 2021-07-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0019_contacts_mysql_id'),
        ('process', '0003_alter_process_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.members'),
        ),
        migrations.AlterField(
            model_name='process',
            name='plot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.plots'),
        ),
    ]
