# Generated by Django 3.2.5 on 2021-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20210723_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='street_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
