# Generated by Django 3.2.5 on 2021-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_process_street_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_data',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_data_back',
            field=models.CharField(blank=True, max_length=26400, null=True),
        ),
    ]
