# Generated by Django 3.2.5 on 2021-07-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20210723_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='member_id',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
