# Generated by Django 3.2.5 on 2021-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_process_comments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_comments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
