# Generated by Django 3.2.4 on 2021-07-14 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=264, null=True)),
                ('userRoleID', models.IntegerField(blank=True, null=True)),
                ('role_short', models.CharField(blank=True, max_length=264, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UsersId', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('admin_id', models.IntegerField(default=1)),
                ('role', models.CharField(blank=True, max_length=264, null=True)),
                ('first_name', models.CharField(blank=True, max_length=264, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=264, null=True)),
                ('last_name', models.CharField(blank=True, max_length=264, null=True)),
                ('father_name', models.CharField(blank=True, max_length=264, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=264, null=True)),
                ('gender', models.CharField(blank=True, max_length=264, null=True)),
                ('cnic', models.CharField(blank=True, max_length=264, null=True)),
                ('Address', models.CharField(blank=True, max_length=264, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=264, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=264, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=2640, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='UserManagement.user_roles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(blank=True, max_length=264, null=True)),
                ('setting_value', models.CharField(blank=True, max_length=264, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settingsUsers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
