# Generated by Django 3.0.5 on 2021-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20210622_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
