# Generated by Django 3.2.4 on 2021-07-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_users_user_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_sign',
        ),
    ]
