# Generated by Django 3.2.4 on 2021-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_remove_users_user_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_sign',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
